export const INPUT_TEXT = "INPUT_TEXT";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const COMMNET_CREATE = "COMMENT_CREATE";
export const COMMENT_DELETE = "COMMENT_DELETE";